spring.application.name=demo
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_QmdHsiOX2
app.gateway.secret=${API_KEY:secreto_local}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
#spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_APP_ID_URI}