name: CI para cloud_native

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: mascotas-back-cont

jobs:
  build_and_push:
    environment: polo_env
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: revision_de_codigo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: build_polo_app
        run: |
          chmod 700 ./gradlew
          ./gradlew bootJar -x test

      - name: login_github_registry
        uses: docker/login-action@v3 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REPOSITORY_TOKEN }}

      - name: build_push_image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: deploy_ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          envs: EC2_IP
          script: |
            echo "-------"
            echo "Longitud del secreto: ${#EC2_IP}"
            echo "Longitud del prueba: #EC2_IP"
            echo "-------"
            if [ ! -f /swapfile ]; then
              sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
              sudo chmod 400 /swapfile
              sudo mkswap /swapfile
              sudo swapon /swapfile
            fi

            if ! command -v docker &> /dev/null; then 
              sudo dnf update -y
              sudo dnf install -y docker
              sudo systemctl enable docker --now
              sudo usermod -aG docker ec2-user
            fi

            sg docker -c "
              docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

              docker stop ${{ env.CONTAINER_NAME }} || true
              docker rm ${{ env.CONTAINER_NAME }} || true
              docker image prune -f

              docker run -d \
                --name ${{ env.CONTAINER_NAME }}
                -p 8080:8080 \
                -e PUBLIC_HOST_URL='http://$EC2_IP' \
                --restart unless-stopped \
                ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            "
        env:
          TARGET_HOST_IP: ${{ secret.EC2_IP }}
          #API_GATEWAY_SECRET: ${{ secrets.API_GATEWAY_SECRET }}
          #GH_CR_PAT: ${{ secrets.GH_CR_PAT }}